steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - {{ cookiecutter.project_slug }}
      - --entry-point={{ cookiecutter.java_package }}.{{ cookiecutter.function_name }}
      - --region={{ cookiecutter.region }}
      - --source=.
      - --trigger-topic={{ cookiecutter.topic_name }}
      - --runtime=java11
      - --memory=256MB
      - --set-env-vars=BUCKET=$_BUCKET,RESULT_FOLDER=$_RESULT_FOLDER,TEMPLATE_FOLDER=$_TEMPLATE_FOLDER
